name: test workflow
on:
  push:
    branches: [testpush]
jobs:
  jobone:
    name: deployment on remote server
    runs-on: ubuntu-latest
    steps:
    - name: ssh to server and running cmds
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 10.1.6.26
        username: root
        password: '@rr!sPor7al'
        port: 22
        proxy_host: spwifi-vpn.arrisi.com
        proxy_username: wibip
        proxy_password: wibip123456
        script: |
          cd /var/www/html/testpull
          git pull origin testpush
          git status
        
        
        
